=== api-evangelist/aerodatabox/json-schema/aerodatabox-flightairportmovementcontract-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "#/components/schemas/FlightAirportMovementContract",
  "title": "FlightAirportMovementContract",
  "required": [
    "airport",
    "quality"
  ],
  "type": "object",
  "properties": {
    "airport": {
      "$ref": "#/components/schemas/ListingAirportContract"
    },
    "scheduledTime": {
      "$ref": "#/components/schemas/DateTimeContract"
    },
    "revisedTime": {
      "$ref": "#/components/schemas/DateTimeContract"
    },
    "predictedTime": {
      "$ref": "#/components/schemas/DateTimeContract"
    },
    "runwayTime": {
      "$ref": "#/components/schemas/DateTimeContract"
    },
    "terminal": {
      "type": "string",
      "description": "Terminal of the flight",
      "nullable": true
    },
    "checkInDesk": {
      "type": "string",
      "description": "Check-in desk(s) for the flight (only for departing flights)",
      "nullable": true
    },
    "gate": {
      "type": "string",
      "description": "Gate of (un)boarding for the flight",
      "nullable": true
    },
    "baggageBelt": {
      "type": "string",
      "description": "Baggage belt(s) for the flight (only for arriving flights)",
      "nullable": true
    },
    "runway": {
      "type": "string",
      "description": "Name of a runway of landing (for arriving flights) or take-off (for departing flights), if known.",
      "nullable": true
    },
    "quality": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/FlightAirportMovementQualityEnum"
      },
      "description": "Array of quality characteristics of the data. Check this to know which information\r\nyou can expect within this contract (basic, live and/or approximate data)."
    }
  },
  "additionalProperties": false,
  "description": "Flight arrival or departure information"
}

=== api-evangelist/aerodatabox/examples/aerodatabox-flight-airport-movement-contract-example.json
{
  "airport": "example_value",
  "scheduledTime": "example_value",
  "revisedTime": "example_value",
  "predictedTime": "example_value",
  "runwayTime": "example_value",
  "terminal": "example_value",
  "checkInDesk": "example_value",
  "gate": "example_value",
  "baggageBelt": "example_value",
  "runway": "example_value",
  "quality": [
    "example_value"
  ]
}
