=== api-evangelist/aerodatabox/json-schema/aerodatabox-airport-contract-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/aerodatabox/refs/heads/main/json-schema/aerodatabox-airport-contract-schema.json",
  "title": "AirportContract",
  "description": "Single airport data",
  "type": "object",
  "properties": {
    "icao": {
      "type": "string",
      "description": "ICAO code of the airport",
      "nullable": true
    },
    "iata": {
      "type": "string",
      "description": "IATA code of the airport",
      "nullable": true
    },
    "localCode": {
      "type": "string",
      "description": "Code of the airport within the local or national coding system",
      "nullable": true
    },
    "shortName": {
      "type": "string",
      "description": "Shortened name of the airport",
      "nullable": true
    },
    "fullName": {
      "minLength": 1,
      "type": "string",
      "description": "Full name of the airport (derived from own airport name and municipality name)"
    },
    "municipalityName": {
      "type": "string",
      "description": "Name of the municipality this airport belongs to",
      "nullable": true
    },
    "location": {
      "$ref": "#/components/schemas/GeoCoordinatesContract"
    },
    "elevation": {
      "$ref": "#/components/schemas/Distance"
    },
    "country": {
      "$ref": "#/components/schemas/CountryContract"
    },
    "continent": {
      "$ref": "#/components/schemas/ContinentContract"
    },
    "timeZone": {
      "minLength": 1,
      "type": "string",
      "description": "Time zone of the airport in Olson format (e.g. \"Europe/Amsterdam\")"
    },
    "urls": {
      "$ref": "#/components/schemas/AirportUrlsContract"
    },
    "runways": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/RunwayContract"
      },
      "description": "List of runway information, if requested",
      "nullable": true
    },
    "currentTime": {
      "$ref": "#/components/schemas/AirportLocalTimeContract"
    }
  },
  "required": [
    "continent",
    "country",
    "elevation",
    "fullName",
    "location",
    "timeZone",
    "urls"
  ],
  "additionalProperties": false
}

=== api-evangelist/aerodatabox/examples/aerodatabox-airport-contract-example.json
{
  "icao": "KLAX",
  "iata": "LAX",
  "localCode": "example_value",
  "shortName": "Los Angeles International",
  "fullName": "Los Angeles International",
  "municipalityName": "Los Angeles International",
  "location": "example_value",
  "elevation": "example_value",
  "country": "example_value",
  "continent": "example_value",
  "timeZone": "example_value",
  "urls": "example_value",
  "runways": [
    "example_value"
  ],
  "currentTime": "example_value"
}
