=== api-evangelist/aerodatabox/json-schema/aerodatabox-aircraft-contract-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/aerodatabox/refs/heads/main/json-schema/aerodatabox-aircraft-contract-schema.json",
  "title": "AircraftContract",
  "description": "Single aircraft data",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "description": "Unique ID of the aircraft record in our database",
      "format": "int64"
    },
    "reg": {
      "minLength": 1,
      "type": "string",
      "description": "Tail-number of the aircraft"
    },
    "active": {
      "type": "boolean",
      "description": "Indicator if aircraft is operational under this registration"
    },
    "serial": {
      "type": "string",
      "description": "Serial number",
      "nullable": true
    },
    "hexIcao": {
      "type": "string",
      "description": "ICAO 24 bit Mode-S hexadecimal transponder address",
      "nullable": true
    },
    "airlineName": {
      "type": "string",
      "description": "Name of the airline operating the aircraft",
      "nullable": true
    },
    "iataType": {
      "type": "string",
      "description": "IATA-type of the aircraft",
      "nullable": true
    },
    "iataCodeShort": {
      "type": "string",
      "description": "Short variant of IATA-code of the aircraft",
      "nullable": true
    },
    "icaoCode": {
      "type": "string",
      "description": "ICAO-code of the aircraft",
      "nullable": true
    },
    "model": {
      "type": "string",
      "description": "Model of the aircraft",
      "nullable": true
    },
    "modelCode": {
      "type": "string",
      "description": "Model code of the aircraft",
      "nullable": true
    },
    "numSeats": {
      "type": "integer",
      "description": "Number of passenger seats",
      "format": "int32",
      "nullable": true
    },
    "rolloutDate": {
      "type": "string",
      "description": "Date of roll-out (UTC)",
      "format": "date-time",
      "nullable": true
    },
    "firstFlightDate": {
      "type": "string",
      "description": "First flight date",
      "format": "date-time",
      "nullable": true
    },
    "deliveryDate": {
      "type": "string",
      "description": "Date of delivery to the owner",
      "format": "date-time",
      "nullable": true
    },
    "registrationDate": {
      "type": "string",
      "description": "Date of assigning current registration",
      "format": "date-time",
      "nullable": true
    },
    "typeName": {
      "type": "string",
      "description": "Type name",
      "nullable": true
    },
    "numEngines": {
      "type": "integer",
      "description": "Number of engines",
      "format": "int32",
      "nullable": true
    },
    "engineType": {
      "$ref": "#/components/schemas/EngineType"
    },
    "isFreighter": {
      "type": "boolean",
      "description": "Marker if aircraft is cargo or not"
    },
    "productionLine": {
      "type": "string",
      "description": "Production line",
      "nullable": true
    },
    "ageYears": {
      "type": "number",
      "description": "Age of the aircraft in year",
      "format": "float",
      "nullable": true
    },
    "verified": {
      "type": "boolean"
    },
    "image": {
      "$ref": "#/components/schemas/ResourceContract"
    },
    "numRegistrations": {
      "type": "integer",
      "description": "An aircraft may have a history of past registrations with other airlines or operators.\r\nThis field represents a total number of registration records known in our database.",
      "format": "int32"
    },
    "registrations": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/AircraftRegistrationContract"
      },
      "description": "A history of all registrations with other airlines or operators (if provided by the endpoint).",
      "nullable": true
    }
  },
  "required": [
    "active",
    "id",
    "isFreighter",
    "numRegistrations",
    "reg",
    "verified"
  ],
  "additionalProperties": false
}

=== api-evangelist/aerodatabox/examples/aerodatabox-aircraft-contract-example.json
{
  "id": 100,
  "reg": "example_value",
  "active": true,
  "serial": "example_value",
  "hexIcao": "KLAX",
  "airlineName": "Los Angeles International",
  "iataType": "LAX",
  "iataCodeShort": "LAX",
  "icaoCode": "KLAX",
  "model": "example_value",
  "modelCode": "example_value",
  "numSeats": 100,
  "rolloutDate": "2025-03-15T14:30:00Z",
  "firstFlightDate": "2025-03-15T14:30:00Z",
  "deliveryDate": "2025-03-15T14:30:00Z",
  "registrationDate": "2025-03-15T14:30:00Z",
  "typeName": "Los Angeles International",
  "numEngines": 100,
  "engineType": "example_value",
  "isFreighter": true,
  "productionLine": "example_value",
  "ageYears": 1.5,
  "verified": true,
  "image": "example_value",
  "numRegistrations": 100,
  "registrations": [
    "example_value"
  ]
}
